version: "3"

services:
  salt-master:
    build:
      context: .
      dockerfile: "salt-master/Dockerfile"
  salt-minion:
    build:
      context: .
      dockerfile: "salt-minion/Dockerfile"
    depends_on:
      - salt-master

